name: mahmoud_task
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Login to Docker Hub
      # run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u omar8magdy --password-stdin
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: omar8magdy
          password: "${{ secrets.DOCKERHUB_TOKEN }}"

      - name: Build Docker image
        run: |
         docker build -t nodejs-api .
         docker tag nodejs-api omar8magdy/nodejs-test:1 
         docker push omar8magdy/nodejs-test:1
      

