name: Mahmoud Task
on:
  push:
    branches:  main
jobs:
  build-Mahmoud:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: main      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_OMAR_MAGDY }}
          password: ${{ secrets.Github_Nodejs_token }}
      - name: run command
        run: |
             npm run docker push omar8magdy/nodejs-test1-node:21.7.2-alpine
             npm i
             npm run build --if-present
             
    
    env: # Or as an environment variable
      super_secret: ${{ secrets.SuperSecret }}
      
  
  deploy:
    needs: build-Mahmoud
    runs-on: ubuntu-latest    
    steps:
      - name: Deploy project   
        run: echo "We are deploying now"
