name: Mahmoud Task
on:
  push:
    branches:  main
jobs:
  build-Mahmoud:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v5
       
      
      - name: run command
        run: |
             npm run docker push omar8magdy/nodejs-test1-node:21.7.2-alpine
             npm i
             npm run build --if-present
             
    
    env: # Or as an environment variable
      super_secret: ${{ secrets.SuperSecret }}
      
  
  deploy:
    needs: build-Mahmoud
    runs-on: ubuntu-latest    
    steps:
      - name: Deploy project   
        run: echo "We are deploying now"
