name: Build and Push Docker Image
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        env:
          DOCKER_TOKEN: ${{ env.DOCKER_TOKEN }}
  
      - run: 
             ${{ env.DOCKER_TOKEN}} 
             docker login -u omar8magdy --password-stdin

      - name: Build Docker image
        run: docker build -t local < .OmarMagdy94/Dockerfile
      - name: Push Docker image
        run: docker push omar8magdy/node:20.0.
