name: Build and Push Docker Image
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u omar8magdy --password-stdin

      - name: Build Docker image
        run: docker build -t local < .omar8magdy/Dockerfile

      - name: Push Docker image
        run: docker push omar8magdy/Dockerfile

