name: Build and Push Docker Image
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        env:
          DOCKER_TOKEN: ${{ env.DOCKER_TOKEN }}
        with: 
         username: omar8magdy 
         password: ${{ secrets.DOCKER_TOKEN }} 
         run: ${{ env.DOCKER_TOKEN}} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build Docker image
        run: docker build -t omar8magdy/node:18.1.

      - name: Push Docker image
        run: docker push omar8magdy/node:18.1.
