name: Mahmoud Task
on:
  push:
    branches:  main
jobs:
  build-Mahmoud:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: main      
      - name: Hello world action
        with: # Set the secret as an input
         super_secret: ${{ secrets.SuperSecret }}
      - name: run command
        run: |
             npm i
             npm run build --if-present
             npm run docker push omar8magdy/nodejs-test1-node:21.7.2-alpine

    
    env: # Or as an environment variable
      super_secret: ${{ secrets.SuperSecret }}
      
  
  deploy:
    needs: build-Mahmoud
    runs-on: ubuntu-latest    
    steps:
      - name: Deploy project   
        run: echo "We are deploying now"
