name: Mahmoud Task
on:
  push:
    branches:  main
jobs:
  build-Mahmoud:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: main      
      - name: run command
        run: |
             npm i
             npm run build --if-present
                 run docker push omar8magdy/nodejs-test1-node:21.7.2-alpine

  
  deploy:
    needs: build-Mahmoud
    runs-on: ubuntu-latest    
    steps:
      - name: Deploy project   
        run: echo "We are deploying now"
